# Generated by Django 3.1.7 on 2021-03-04 21:37

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('score', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=20)),
                ('hits', models.PositiveIntegerField()),
                ('mistakes', models.PositiveIntegerField()),
                ('individual_feedback', models.TextField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.player')),
            ],
        ),
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(max_length=250)),
                ('concept', models.CharField(max_length=150)),
                ('is_mistake', models.BooleanField()),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.match')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.group'),
        ),
    ]
