# Generated by Django 3.1.7 on 2021-03-04 22:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210304_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='match_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
